name: learn-github-actions

on: 
  push:
    branches:
      - main
      - stg
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: Get changed files
        run: | 
          git log --pretty=oneline "${{ github.event.before }}...${{ github.event.after }}"
