name: learn-github-actions

on: 
  push:
    branches:
      - main
      - stg
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          